<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup> 
  
  <ItemGroup>
    <ProjectReference Include="..\Papercut.Common\Papercut.Common.csproj">
    </ProjectReference>
    <ProjectReference Include="..\Papercut.Core\Papercut.Core.csproj">
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Autofac">
      <Version>9.3.2</Version>
    </PackageReference>
    <PackageReference Include="MailKit">
      <Version>4.17.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="MimeKit">
      <Version>4.17.0</Version>
    </PackageReference>
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="JetBrains.Annotations" Version="2026.2.0" />
  </ItemGroup>
</Project>