//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("5.8.1.0")]
[assembly: AssemblyFileVersion("5.8.1.0")]
[assembly: AssemblyInformationalVersion("5.8.1-NewHTMLRender.16+Branch.NewHTMLRender.Sha.742077df6313ceb4badeb4c2f241fce6a999588c")]

