//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("5.7.0.1")]
[assembly: AssemblyFileVersion("5.7.0.0")]
[assembly: AssemblyInformationalVersion("5.7.0-alpha.1+Branch.develop.Sha.261f93f0bfb133370872bf04ec42e4f1cc4b3360")]

